### PR TITLE
User authentication

### PR DESCRIPTION
**Pull request by ryandelvecchio**

### CODE REVIEW

**Review by carteralbrecht — COMMENTED** [review]
Should we include the login pages too @ryandelvecchio ? I think someone else worked on that too. I like these, personally.

**Review by carteralbrecht — COMMENTED** [review]
Also, this only includes the create user endpoint right @ryandelvecchio

**Comment by ryandelvecchio** [comment]
> Also, this only includes the create user endpoint right @ryandelvecchio

It is login and registration.  The endpoint you see for creating users is only used internally because we need to create the user using an admin okta client.  We do not need one for login.  I believe we could use the login endpoint on okta but the auth SDK on web and mobile handles that for us. 

> Should we include the login pages too @ryandelvecchio ? I think someone else worked on that too. I like these, personally.

I don't mind either way.  We can merge it for now and edit/overwrite it if we want to go with something else.

**Comment by carteralbrecht** [comment]
Sounds good. If a better login page comes along we can change..

**Review by carteralbrecht — APPROVED** [review]

**Review by cjack0416 — APPROVED** [review]

**Review by cjack0416 — APPROVED** [review]
Not sure if I had to leave a comment but here you go.

**Comment by carteralbrecht** [comment]
Needs another approval by someone who has write access (accepted invite already)

**Comment by carteralbrecht** [comment]
changed number of reviews required to 1...

**Pull request merged**
